name: minfo_sdk
description: Minfo SDK for Flutter - AudioQR powered engagement platform
version: 2.3.1
repository: https://github.com/codelab-bj/minfoSdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.0
  http: ^1.1.0
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.5
  device_info_plus: ^9.1.0
  package_info_plus: ^5.0.0
  uuid: ^4.2.0
  cached_network_image: ^3.3.1

  permission_handler: ^11.0.0
  audio_session: ^0.1.16
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.minfo_sdk
        pluginClass: MinfoSdkPlugin
      ios:
        pluginClass: MinfoSdkPlugin
